version: 2

project_name: xlistman

builds:
  - env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w -X github.com/barats/xlistman/cmd.Version={{.Version}}
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64

archives:
  - format: tar.gz
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"

checksum:
  name_template: "checksums.txt"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

release:
  github:
    owner: barats
    name: xlistman
